name: Download and Commit Files

on:
  schedule:
    # Har kuni soat 00:00 da ishga tushadi
    - cron: "0 0 * * *"

jobs:
  download_and_commit:
    runs-on: ubuntu-latest

    steps:
      # Repository-ni checkout qilish
      - name: Checkout repository
        uses: actions/checkout@v3

      # Resources papkasidagi eski fayllarni o'chirish
      - name: Clean resources folder
        run: |
          mkdir -p resources
          rm -rf resources/*

      # CSV faylni yuklab olish
      - name: Download CSV file
        run: curl -o resources/bad_words.csv ${{ secrets.CSV_FILE_URL }}

      # JSON faylni yuklab olish
      - name: Download JSON file
        run: curl -o resources/bad_words.json ${{ secrets.JSON_FILE_URL }}

      # XLSX faylni yuklab olish
      - name: Download XLSX file
        run: curl -o resources/bad_words.xlsx ${{ secrets.XLSX_FILE_URL }}

      # O'zgarishlarni repositoryga qo'shish
      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add resources/*
            git commit -m "Auto-update: $(date +"%Y-%m-%d %H:%M:%S")"
            git push
          else
            echo "No changes to commit."
          fi
